//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asset_OracleLogger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<SV_SERVICEDETAILS> SV_SERVICEDETAILS { get; set; }
        public DbSet<SV_LOGGER> SV_LOGGER { get; set; }
    
        public virtual int ADD_SERVICELOGGER(string p_PROGRAM, string p_PROJECT, string p_RELEASE, string p_APIOPERATION, string p_SPRINT, string p_KEYDATA, string p_METHOD, string p_URI, string p_RESPONSE, string p_REQUEST)
        {
            var p_PROGRAMParameter = p_PROGRAM != null ?
                new ObjectParameter("P_PROGRAM", p_PROGRAM) :
                new ObjectParameter("P_PROGRAM", typeof(string));
    
            var p_PROJECTParameter = p_PROJECT != null ?
                new ObjectParameter("P_PROJECT", p_PROJECT) :
                new ObjectParameter("P_PROJECT", typeof(string));
    
            var p_RELEASEParameter = p_RELEASE != null ?
                new ObjectParameter("P_RELEASE", p_RELEASE) :
                new ObjectParameter("P_RELEASE", typeof(string));
    
            var p_APIOPERATIONParameter = p_APIOPERATION != null ?
                new ObjectParameter("P_APIOPERATION", p_APIOPERATION) :
                new ObjectParameter("P_APIOPERATION", typeof(string));
    
            var p_SPRINTParameter = p_SPRINT != null ?
                new ObjectParameter("P_SPRINT", p_SPRINT) :
                new ObjectParameter("P_SPRINT", typeof(string));
    
            var p_KEYDATAParameter = p_KEYDATA != null ?
                new ObjectParameter("P_KEYDATA", p_KEYDATA) :
                new ObjectParameter("P_KEYDATA", typeof(string));
    
            var p_METHODParameter = p_METHOD != null ?
                new ObjectParameter("P_METHOD", p_METHOD) :
                new ObjectParameter("P_METHOD", typeof(string));
    
            var p_URIParameter = p_URI != null ?
                new ObjectParameter("P_URI", p_URI) :
                new ObjectParameter("P_URI", typeof(string));
    
            var p_RESPONSEParameter = p_RESPONSE != null ?
                new ObjectParameter("P_RESPONSE", p_RESPONSE) :
                new ObjectParameter("P_RESPONSE", typeof(string));
    
            var p_REQUESTParameter = p_REQUEST != null ?
                new ObjectParameter("P_REQUEST", p_REQUEST) :
                new ObjectParameter("P_REQUEST", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_SERVICELOGGER", p_PROGRAMParameter, p_PROJECTParameter, p_RELEASEParameter, p_APIOPERATIONParameter, p_SPRINTParameter, p_KEYDATAParameter, p_METHODParameter, p_URIParameter, p_RESPONSEParameter, p_REQUESTParameter);
        }
    
        public virtual int LOGGER_GETLIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LOGGER_GETLIST");
        }
    
        public virtual int ADD_SERVICEDETAILS(string p_PROGRAM, string p_PROJECT, string p_RELEASE, string p_APIOPERATION, string p_SPRINT, string p_ARGUMENT1, string p_ARGUMENTVALUE1, string p_ARGUMENT2, string p_ARGUMENTVALUE2, string p_ARGUMENT3, string p_ARGUMENTVALUE3, string p_ARGUMENT4, string p_ARGUMENTVALUE4, string p_ARGUMENT5, string p_ARGUMENTVALUE5, string p_REQUESTHEADER1, string p_REQUESTHEADERVALUE1, string p_REQUESTHEADER2, string p_REQUESTHEADERVALUE2, string p_REQUESTHEADER3, string p_REQUESTHEADERVALUE3, string p_RESPONSEHEADER1, string p_RESPONSEHEADERVALUE1, string p_RESPONSEHEADER2, string p_RESPONSEHEADERVALUE2, string p_LIVESERVER, Nullable<decimal> p_LIVEPORT, string p_METHOD, string p_URI, string p_LASTMODIFIEDBY, string p_USERID, Nullable<decimal> p_NUMBEROFMODIFICTIONS, string p_RESPONSE, string p_REQUEST, string p_SERVICETYPE)
        {
            var p_PROGRAMParameter = p_PROGRAM != null ?
                new ObjectParameter("P_PROGRAM", p_PROGRAM) :
                new ObjectParameter("P_PROGRAM", typeof(string));
    
            var p_PROJECTParameter = p_PROJECT != null ?
                new ObjectParameter("P_PROJECT", p_PROJECT) :
                new ObjectParameter("P_PROJECT", typeof(string));
    
            var p_RELEASEParameter = p_RELEASE != null ?
                new ObjectParameter("P_RELEASE", p_RELEASE) :
                new ObjectParameter("P_RELEASE", typeof(string));
    
            var p_APIOPERATIONParameter = p_APIOPERATION != null ?
                new ObjectParameter("P_APIOPERATION", p_APIOPERATION) :
                new ObjectParameter("P_APIOPERATION", typeof(string));
    
            var p_SPRINTParameter = p_SPRINT != null ?
                new ObjectParameter("P_SPRINT", p_SPRINT) :
                new ObjectParameter("P_SPRINT", typeof(string));
    
            var p_ARGUMENT1Parameter = p_ARGUMENT1 != null ?
                new ObjectParameter("P_ARGUMENT1", p_ARGUMENT1) :
                new ObjectParameter("P_ARGUMENT1", typeof(string));
    
            var p_ARGUMENTVALUE1Parameter = p_ARGUMENTVALUE1 != null ?
                new ObjectParameter("P_ARGUMENTVALUE1", p_ARGUMENTVALUE1) :
                new ObjectParameter("P_ARGUMENTVALUE1", typeof(string));
    
            var p_ARGUMENT2Parameter = p_ARGUMENT2 != null ?
                new ObjectParameter("P_ARGUMENT2", p_ARGUMENT2) :
                new ObjectParameter("P_ARGUMENT2", typeof(string));
    
            var p_ARGUMENTVALUE2Parameter = p_ARGUMENTVALUE2 != null ?
                new ObjectParameter("P_ARGUMENTVALUE2", p_ARGUMENTVALUE2) :
                new ObjectParameter("P_ARGUMENTVALUE2", typeof(string));
    
            var p_ARGUMENT3Parameter = p_ARGUMENT3 != null ?
                new ObjectParameter("P_ARGUMENT3", p_ARGUMENT3) :
                new ObjectParameter("P_ARGUMENT3", typeof(string));
    
            var p_ARGUMENTVALUE3Parameter = p_ARGUMENTVALUE3 != null ?
                new ObjectParameter("P_ARGUMENTVALUE3", p_ARGUMENTVALUE3) :
                new ObjectParameter("P_ARGUMENTVALUE3", typeof(string));
    
            var p_ARGUMENT4Parameter = p_ARGUMENT4 != null ?
                new ObjectParameter("P_ARGUMENT4", p_ARGUMENT4) :
                new ObjectParameter("P_ARGUMENT4", typeof(string));
    
            var p_ARGUMENTVALUE4Parameter = p_ARGUMENTVALUE4 != null ?
                new ObjectParameter("P_ARGUMENTVALUE4", p_ARGUMENTVALUE4) :
                new ObjectParameter("P_ARGUMENTVALUE4", typeof(string));
    
            var p_ARGUMENT5Parameter = p_ARGUMENT5 != null ?
                new ObjectParameter("P_ARGUMENT5", p_ARGUMENT5) :
                new ObjectParameter("P_ARGUMENT5", typeof(string));
    
            var p_ARGUMENTVALUE5Parameter = p_ARGUMENTVALUE5 != null ?
                new ObjectParameter("P_ARGUMENTVALUE5", p_ARGUMENTVALUE5) :
                new ObjectParameter("P_ARGUMENTVALUE5", typeof(string));
    
            var p_REQUESTHEADER1Parameter = p_REQUESTHEADER1 != null ?
                new ObjectParameter("P_REQUESTHEADER1", p_REQUESTHEADER1) :
                new ObjectParameter("P_REQUESTHEADER1", typeof(string));
    
            var p_REQUESTHEADERVALUE1Parameter = p_REQUESTHEADERVALUE1 != null ?
                new ObjectParameter("P_REQUESTHEADERVALUE1", p_REQUESTHEADERVALUE1) :
                new ObjectParameter("P_REQUESTHEADERVALUE1", typeof(string));
    
            var p_REQUESTHEADER2Parameter = p_REQUESTHEADER2 != null ?
                new ObjectParameter("P_REQUESTHEADER2", p_REQUESTHEADER2) :
                new ObjectParameter("P_REQUESTHEADER2", typeof(string));
    
            var p_REQUESTHEADERVALUE2Parameter = p_REQUESTHEADERVALUE2 != null ?
                new ObjectParameter("P_REQUESTHEADERVALUE2", p_REQUESTHEADERVALUE2) :
                new ObjectParameter("P_REQUESTHEADERVALUE2", typeof(string));
    
            var p_REQUESTHEADER3Parameter = p_REQUESTHEADER3 != null ?
                new ObjectParameter("P_REQUESTHEADER3", p_REQUESTHEADER3) :
                new ObjectParameter("P_REQUESTHEADER3", typeof(string));
    
            var p_REQUESTHEADERVALUE3Parameter = p_REQUESTHEADERVALUE3 != null ?
                new ObjectParameter("P_REQUESTHEADERVALUE3", p_REQUESTHEADERVALUE3) :
                new ObjectParameter("P_REQUESTHEADERVALUE3", typeof(string));
    
            var p_RESPONSEHEADER1Parameter = p_RESPONSEHEADER1 != null ?
                new ObjectParameter("P_RESPONSEHEADER1", p_RESPONSEHEADER1) :
                new ObjectParameter("P_RESPONSEHEADER1", typeof(string));
    
            var p_RESPONSEHEADERVALUE1Parameter = p_RESPONSEHEADERVALUE1 != null ?
                new ObjectParameter("P_RESPONSEHEADERVALUE1", p_RESPONSEHEADERVALUE1) :
                new ObjectParameter("P_RESPONSEHEADERVALUE1", typeof(string));
    
            var p_RESPONSEHEADER2Parameter = p_RESPONSEHEADER2 != null ?
                new ObjectParameter("P_RESPONSEHEADER2", p_RESPONSEHEADER2) :
                new ObjectParameter("P_RESPONSEHEADER2", typeof(string));
    
            var p_RESPONSEHEADERVALUE2Parameter = p_RESPONSEHEADERVALUE2 != null ?
                new ObjectParameter("P_RESPONSEHEADERVALUE2", p_RESPONSEHEADERVALUE2) :
                new ObjectParameter("P_RESPONSEHEADERVALUE2", typeof(string));
    
            var p_LIVESERVERParameter = p_LIVESERVER != null ?
                new ObjectParameter("P_LIVESERVER", p_LIVESERVER) :
                new ObjectParameter("P_LIVESERVER", typeof(string));
    
            var p_LIVEPORTParameter = p_LIVEPORT.HasValue ?
                new ObjectParameter("P_LIVEPORT", p_LIVEPORT) :
                new ObjectParameter("P_LIVEPORT", typeof(decimal));
    
            var p_METHODParameter = p_METHOD != null ?
                new ObjectParameter("P_METHOD", p_METHOD) :
                new ObjectParameter("P_METHOD", typeof(string));
    
            var p_URIParameter = p_URI != null ?
                new ObjectParameter("P_URI", p_URI) :
                new ObjectParameter("P_URI", typeof(string));
    
            var p_LASTMODIFIEDBYParameter = p_LASTMODIFIEDBY != null ?
                new ObjectParameter("P_LASTMODIFIEDBY", p_LASTMODIFIEDBY) :
                new ObjectParameter("P_LASTMODIFIEDBY", typeof(string));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("P_USERID", p_USERID) :
                new ObjectParameter("P_USERID", typeof(string));
    
            var p_NUMBEROFMODIFICTIONSParameter = p_NUMBEROFMODIFICTIONS.HasValue ?
                new ObjectParameter("P_NUMBEROFMODIFICTIONS", p_NUMBEROFMODIFICTIONS) :
                new ObjectParameter("P_NUMBEROFMODIFICTIONS", typeof(decimal));
    
            var p_RESPONSEParameter = p_RESPONSE != null ?
                new ObjectParameter("P_RESPONSE", p_RESPONSE) :
                new ObjectParameter("P_RESPONSE", typeof(string));
    
            var p_REQUESTParameter = p_REQUEST != null ?
                new ObjectParameter("P_REQUEST", p_REQUEST) :
                new ObjectParameter("P_REQUEST", typeof(string));
    
            var p_SERVICETYPEParameter = p_SERVICETYPE != null ?
                new ObjectParameter("P_SERVICETYPE", p_SERVICETYPE) :
                new ObjectParameter("P_SERVICETYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_SERVICEDETAILS", p_PROGRAMParameter, p_PROJECTParameter, p_RELEASEParameter, p_APIOPERATIONParameter, p_SPRINTParameter, p_ARGUMENT1Parameter, p_ARGUMENTVALUE1Parameter, p_ARGUMENT2Parameter, p_ARGUMENTVALUE2Parameter, p_ARGUMENT3Parameter, p_ARGUMENTVALUE3Parameter, p_ARGUMENT4Parameter, p_ARGUMENTVALUE4Parameter, p_ARGUMENT5Parameter, p_ARGUMENTVALUE5Parameter, p_REQUESTHEADER1Parameter, p_REQUESTHEADERVALUE1Parameter, p_REQUESTHEADER2Parameter, p_REQUESTHEADERVALUE2Parameter, p_REQUESTHEADER3Parameter, p_REQUESTHEADERVALUE3Parameter, p_RESPONSEHEADER1Parameter, p_RESPONSEHEADERVALUE1Parameter, p_RESPONSEHEADER2Parameter, p_RESPONSEHEADERVALUE2Parameter, p_LIVESERVERParameter, p_LIVEPORTParameter, p_METHODParameter, p_URIParameter, p_LASTMODIFIEDBYParameter, p_USERIDParameter, p_NUMBEROFMODIFICTIONSParameter, p_RESPONSEParameter, p_REQUESTParameter, p_SERVICETYPEParameter);
        }
    
        public virtual int ADD_SOAPDETAILS(string p_PROGRAM, string p_PROJECT, string p_RELEASE, string p_OPERATION, string p_SPRINT, string p_ARGUMENT1, string p_ARGUMENTVALUE1, string p_ARGUMENT2, string p_ARGUMENTVALUE2, string p_ARGUMENT3, string p_ARGUMENTVALUE3, string p_ARGUMENT4, string p_ARGUMENTVALUE4, string p_ARGUMENT5, string p_ARGUMENTVALUE5, string p_LASTMODIFIEDBY, string p_USERID, Nullable<decimal> p_NUMBEROFMODIFICTIONS, string p_RESPONSE, string p_REQUEST, string p_SERVICETYPE)
        {
            var p_PROGRAMParameter = p_PROGRAM != null ?
                new ObjectParameter("P_PROGRAM", p_PROGRAM) :
                new ObjectParameter("P_PROGRAM", typeof(string));
    
            var p_PROJECTParameter = p_PROJECT != null ?
                new ObjectParameter("P_PROJECT", p_PROJECT) :
                new ObjectParameter("P_PROJECT", typeof(string));
    
            var p_RELEASEParameter = p_RELEASE != null ?
                new ObjectParameter("P_RELEASE", p_RELEASE) :
                new ObjectParameter("P_RELEASE", typeof(string));
    
            var p_OPERATIONParameter = p_OPERATION != null ?
                new ObjectParameter("P_OPERATION", p_OPERATION) :
                new ObjectParameter("P_OPERATION", typeof(string));
    
            var p_SPRINTParameter = p_SPRINT != null ?
                new ObjectParameter("P_SPRINT", p_SPRINT) :
                new ObjectParameter("P_SPRINT", typeof(string));
    
            var p_ARGUMENT1Parameter = p_ARGUMENT1 != null ?
                new ObjectParameter("P_ARGUMENT1", p_ARGUMENT1) :
                new ObjectParameter("P_ARGUMENT1", typeof(string));
    
            var p_ARGUMENTVALUE1Parameter = p_ARGUMENTVALUE1 != null ?
                new ObjectParameter("P_ARGUMENTVALUE1", p_ARGUMENTVALUE1) :
                new ObjectParameter("P_ARGUMENTVALUE1", typeof(string));
    
            var p_ARGUMENT2Parameter = p_ARGUMENT2 != null ?
                new ObjectParameter("P_ARGUMENT2", p_ARGUMENT2) :
                new ObjectParameter("P_ARGUMENT2", typeof(string));
    
            var p_ARGUMENTVALUE2Parameter = p_ARGUMENTVALUE2 != null ?
                new ObjectParameter("P_ARGUMENTVALUE2", p_ARGUMENTVALUE2) :
                new ObjectParameter("P_ARGUMENTVALUE2", typeof(string));
    
            var p_ARGUMENT3Parameter = p_ARGUMENT3 != null ?
                new ObjectParameter("P_ARGUMENT3", p_ARGUMENT3) :
                new ObjectParameter("P_ARGUMENT3", typeof(string));
    
            var p_ARGUMENTVALUE3Parameter = p_ARGUMENTVALUE3 != null ?
                new ObjectParameter("P_ARGUMENTVALUE3", p_ARGUMENTVALUE3) :
                new ObjectParameter("P_ARGUMENTVALUE3", typeof(string));
    
            var p_ARGUMENT4Parameter = p_ARGUMENT4 != null ?
                new ObjectParameter("P_ARGUMENT4", p_ARGUMENT4) :
                new ObjectParameter("P_ARGUMENT4", typeof(string));
    
            var p_ARGUMENTVALUE4Parameter = p_ARGUMENTVALUE4 != null ?
                new ObjectParameter("P_ARGUMENTVALUE4", p_ARGUMENTVALUE4) :
                new ObjectParameter("P_ARGUMENTVALUE4", typeof(string));
    
            var p_ARGUMENT5Parameter = p_ARGUMENT5 != null ?
                new ObjectParameter("P_ARGUMENT5", p_ARGUMENT5) :
                new ObjectParameter("P_ARGUMENT5", typeof(string));
    
            var p_ARGUMENTVALUE5Parameter = p_ARGUMENTVALUE5 != null ?
                new ObjectParameter("P_ARGUMENTVALUE5", p_ARGUMENTVALUE5) :
                new ObjectParameter("P_ARGUMENTVALUE5", typeof(string));
    
            var p_LASTMODIFIEDBYParameter = p_LASTMODIFIEDBY != null ?
                new ObjectParameter("P_LASTMODIFIEDBY", p_LASTMODIFIEDBY) :
                new ObjectParameter("P_LASTMODIFIEDBY", typeof(string));
    
            var p_USERIDParameter = p_USERID != null ?
                new ObjectParameter("P_USERID", p_USERID) :
                new ObjectParameter("P_USERID", typeof(string));
    
            var p_NUMBEROFMODIFICTIONSParameter = p_NUMBEROFMODIFICTIONS.HasValue ?
                new ObjectParameter("P_NUMBEROFMODIFICTIONS", p_NUMBEROFMODIFICTIONS) :
                new ObjectParameter("P_NUMBEROFMODIFICTIONS", typeof(decimal));
    
            var p_RESPONSEParameter = p_RESPONSE != null ?
                new ObjectParameter("P_RESPONSE", p_RESPONSE) :
                new ObjectParameter("P_RESPONSE", typeof(string));
    
            var p_REQUESTParameter = p_REQUEST != null ?
                new ObjectParameter("P_REQUEST", p_REQUEST) :
                new ObjectParameter("P_REQUEST", typeof(string));
    
            var p_SERVICETYPEParameter = p_SERVICETYPE != null ?
                new ObjectParameter("P_SERVICETYPE", p_SERVICETYPE) :
                new ObjectParameter("P_SERVICETYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ADD_SOAPDETAILS", p_PROGRAMParameter, p_PROJECTParameter, p_RELEASEParameter, p_OPERATIONParameter, p_SPRINTParameter, p_ARGUMENT1Parameter, p_ARGUMENTVALUE1Parameter, p_ARGUMENT2Parameter, p_ARGUMENTVALUE2Parameter, p_ARGUMENT3Parameter, p_ARGUMENTVALUE3Parameter, p_ARGUMENT4Parameter, p_ARGUMENTVALUE4Parameter, p_ARGUMENT5Parameter, p_ARGUMENTVALUE5Parameter, p_LASTMODIFIEDBYParameter, p_USERIDParameter, p_NUMBEROFMODIFICTIONSParameter, p_RESPONSEParameter, p_REQUESTParameter, p_SERVICETYPEParameter);
        }
    }
}
