//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asset_OracleLogger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV_SERVICEDETAILS
    {
        public decimal ID { get; set; }
        public string PROGRAM { get; set; }
        public string PROJECT { get; set; }
        public string RELEASE { get; set; }
        public string APIOPERATION { get; set; }
        public string SPRINT { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<System.DateTime> LASTMODIFIEDDATE { get; set; }
        public string ARGUMENT1 { get; set; }
        public string ARGUMENT2 { get; set; }
        public string ARGUMENTVALUE2 { get; set; }
        public string ARGUMENTVALUE3 { get; set; }
        public string ARGUMENT4 { get; set; }
        public string ARGUMENTVALUE4 { get; set; }
        public string ARGUMENT5 { get; set; }
        public string ARGUMENTVALUE5 { get; set; }
        public string REQUESTHEADER1 { get; set; }
        public string REQUESTHEADERVALUE1 { get; set; }
        public string REQUESTHEADER2 { get; set; }
        public string REQUESTHEADERVALUE2 { get; set; }
        public string REQUESTHEADER3 { get; set; }
        public string REQUESTHEADERVALUE3 { get; set; }
        public string RESPONSEHEADER1 { get; set; }
        public string RESPONSEHEADERVALUE1 { get; set; }
        public string RESPONSEHEADER2 { get; set; }
        public string RESPONSEHEADERVALUE2 { get; set; }
        public string LIVESERVER { get; set; }
        public Nullable<decimal> LIVEPORT { get; set; }
        public string METHOD { get; set; }
        public string URI { get; set; }
        public string LASTMODIFIEDBY { get; set; }
        public string USERID { get; set; }
        public string ARGUMENTVALUE1 { get; set; }
        public Nullable<decimal> NUMOFMODIFICATIONS { get; set; }
        public string ARGUMENT3 { get; set; }
        public string REQUEST { get; set; }
        public string RESPONSE { get; set; }
        public string OPERATION { get; set; }
        public string SERVICETYPE { get; set; }
    }
}
